name: deeplens
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  
  # CUDA 12.4 SDK components (compatible with your CUDA 12.9 runtime)
  - cuda-toolkit=12.4
  - cuda-nvcc=12.4
  - cuda-cudart=12.4
  - cuda-nvtx=12.4
  - cuda-cupti=12.4
  - cuda-nvrtc=12.4
  - cuda-libraries=12.4
  - cuda-runtime=12.4
  - cuda-version=12.4
  
  # Math backends
  - mkl
  - blas=1.0=mkl
  - intel-openmp
  
  # Core packages
  - numpy<2.0  # Force NumPy 1.x for PyTorch compatibility
  - scipy
  - matplotlib
  - pillow
  - scikit-image
  - networkx
  - pyyaml
  - requests
  - tqdm
  - imageio
  - setuptools
  - wheel
  - packaging
  - six
  - jinja2
  - markupsafe
  - tornado
  - filelock
  - typing_extensions
  - certifi
  - urllib3
  - charset-normalizer
  - idna
  - libjpeg-turbo
  - libpng
  - jpeg
  
  # PyTorch with CUDA support (let conda resolve compatible versions)
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  # - pytorch
  # - torchvision
  # - torchaudio
  # - pytorch-cuda=12.4
  - pytorch-mutex=1.0=cuda
  
  # GUI packages
  - pyqt
  #- qt-main

  # Qt 6.7 packages
  - qt6-main=6.7.*
  - qtconsole
  
  # System utilities
  - openssl
  - ca-certificates
  - sqlite
  - zlib
  - bzip2
  - expat
  - libpng
  - jpeg
  - freetype
  - fontconfig
  
  - pip:
      # Core ML/AI packages
      - annotated-types==0.7.0
      - click==8.1.8
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.30.1
      - lpips==0.1.4
      - opencv-python==4.11.0.86
      - platformdirs==4.3.7
      - protobuf==5.29.4
      - psutil==7.0.0
      - pydantic==2.11.2
      - pydantic-core==2.33.1
      - regex==2024.11.6
      - safetensors==0.5.3
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - smmap==5.0.2
      - sympy==1.13.1
      - tokenizers==0.21.1
      - transformers==4.51.0
      - typing-inspection==0.4.0
      - wandb==0.19.9
      # 3D visualization packages
      - pyvista==0.44.2
      - pyvistaqt==0.11.2